name:       geomancy
version:    0.2.4.0
git:        "https://gitlab.com/dpwiz/geomancy"
license:    BSD3
author:     "Alexander Bondarenko"
maintainer: "aenor.realm@gmail.com"
copyright:  "2021 Alexander Bondarenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Geometry and matrix manipulation
category: Graphics

description: |
  Sometimes it is unavoidable you have to do stuff on CPU.
  Let's at least do it faster.

dependencies:
- base >= 4.7 && < 5
- deepseq
- simple-affine-space

ghc-options:
- -Wall

library:
  c-sources: cbits/mat4.c
  source-dirs: src
  dependencies:
  - containers

tests:
  geomancy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-qn1
    - -with-rtsopts=-A128m
    # - -with-rtsopts=-s
    dependencies:
    - geomancy
    - linear
    - hedgehog

benchmarks:
  geomancy-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-qn1
    - -with-rtsopts=-A16m
    dependencies:
    - geomancy
    - linear
    - criterion
