name:       geomancy
version:    0.1.1.0
git:        "https://gitlab.com/dpwiz/geomancy"
license:    BSD3
author:     "Alexander Bondarenko"
maintainer: "aenor.realm@gmail.com"
copyright:  "2020 Alexander Bondarenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Geometry and matrix manipulation
category: Graphics

description: |
  Sometimes it is unavoidable you have to do stuff on CPU.
  Let's at least do it faster.

dependencies:
- base >= 4.7 && < 5

library:
  c-sources: cbits/mat4.c
  source-dirs: src

tests:
  geomancy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geomancy
