resolver: https://gitlab.com/keid/meta/-/raw/main/resolvers/keid-engine-2023-04-07.yaml

packages:
- .

extra-deps:
- ptrdiff-0

system-ghc: true
ghc-options:
  "$everything": -split-sections -j2
  "$locals": -split-sections -j8
